# Generated by Django 6.0.4 on 2026-05-25 12:19

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0234_cablepath_nodes_index'),
        ('extras', '0138_customfieldchoiceset_choice_colors'),
        ('tenancy', '0024_default_ordering_indexes'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('cross_connect_id', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Cross connect ID must match the format ID-<CODE>-<5 digits>.', regex='^ID-[A-Z0-9]+-\\d{5}$')])),
                ('ritm', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='RITM must match the format RITM#######.', regex='^RITM\\d{7}$')])),
                ('status', models.CharField(default='planned', max_length=50)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('last_known_path', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_connects', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_connects', to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'cross connect',
                'verbose_name_plural': 'cross connects',
                'ordering': ('cross_connect_id',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
