# Generated by Django 6.0.4 on 2026-05-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cross_connects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossconnect',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
    ]
