# Generated by Django 6.0.4 on 2026-05-26 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cross_connects', '0002_alter_crossconnect_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossconnect',
            name='cross_connect_id',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Cross connect ID must match the format ID-<CODE>-<5 digits>.', regex='^ID-[A-Z0-9]+-\\d{5}$')]),
        ),
    ]
