# Generated by Django 5.2.9 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_cross_connects', '0004_validate_attachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossconnect',
            name='cross_review',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('reviewed', 'Reviewed'),
                ],
                default='pending',
                max_length=20,
            ),
        ),
    ]
